name: Deploy Flutter Web

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Enable web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --base-href /fortetude/ --dart-define=GOOGLE_FORMS_URL=${{ secrets.GOOGLE_FORMS_URL }}

      - name: Add SPA fallback
        run: cp build/web/index.html build/web/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4